services:
  - type: web
    name: latex-editor
    env: node
    buildCommand: bash ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
